print('Hello,World!')
print('What is your name?')
my_name = input()
print('Nice to meet you, ' + my_name)
print('The lengs of your name is :')
print(len(my_name))
print('What is your age?')
my_age = input()
print('You will be ' + str(int(my_age) +1) + ' in a year.')
