print('Hello World')
print('What is your name?')
my_name = input('name:')
print('It is good to see you,' + my_name)
print('How long length of your name?')
print('We think The length of your name is :',end=' ')
print(len(my_name))
print('what is your age?')
my_age = input('age:')
print('You will be ' + str(int(my_age)+1) + ' in a year')