print('Hello World')
print('What is your name?')
name = input('名前:')
print('It is good your name is : ' + name)
print('The length of your name is : ',end ='')
print(len(name))
print('What is your age? ')
age = input('年齢:')
print('You will be ' + str(int(age) + 1) + 'next year')